name: sparksos2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0  # Updated for null safety
  permission_handler: ^11.1.0  # Updated for null safety
  telephony: ^0.2.0
  shared_preferences: ^2.2.2  # Updated for null safety
  flutter_sms: ^2.3.3  # Alternative SMS package with null safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # Updated version

flutter:
  uses-material-design: true